import Banner from './home/banner';
import Campaigns from './home/campaigns';
import Competitors from './home/competitors';
import Partner from './home/partner';
import Services from './home/services';
import Solution from './home/solution';

export const metadata = {
  title: "Home Page TEST | Click First",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Banner />
      <Partner />
      <Services />
      <Solution />
      <Competitors />
      <Campaigns />
    </>
  );
}
