import Banner from '@/src/app/home/banner';
import Brand from '@/src/app/home/brand';
import Campaigns from '@/src/app/home/campaigns';
import Competitors from '@/src/app/home/competitors';
import Partner from '@/src/app/home/partner';
import Services from '@/src/app/home/services';
import Solution from '@/src/app/home/solution';
import Guide from '@/src/app/home/guide';
import Platforms from '@/src/components/platforms';
import Creation from '@/src/app/home/creation';
import Industries from '@/src/app/home/industries';
import Priceing from '@/src/app/home/priceing';
import Testimonials from './home/testimonials';
import CtaComp from '../components/cta';

export const metadata = {
  title: "Home Page | Click First",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Banner />
      <Partner />
      <Services />
      <Solution />
      <Competitors />
      <Campaigns />
      <Brand />
      <Guide />
      <Platforms />
      <Creation />
      <Industries />
      <Priceing />
      <Testimonials />
      <CtaComp />
    </>
  );
}
